require('dotenv').config({ path: '../.env' });
const mongoose = require('mongoose');
const Exercise = require('../models/Exercise');

const connectDB = async () => {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('✅ Connected to Gymmix DB for seeding');
};

const exercises = [
  // ── CHEST ──────────────────────────────────────────────
  { name: 'Barbell Bench Press', description: 'Classic compound chest exercise using a barbell.', instructions: ['Lie flat on bench', 'Grip bar slightly wider than shoulder width', 'Lower bar to mid-chest', 'Press up explosively'], muscleGroups: ['chest', 'triceps', 'shoulders'], primaryMuscle: 'chest', equipment: 'barbell', difficultyLevel: 'intermediate', category: 'strength', defaultSets: 4, defaultReps: '6-10', defaultRestSeconds: 90, tags: ['compound', 'push', 'chest'] },
  { name: 'Incline Dumbbell Press', description: 'Targets upper chest at a 30-45 degree incline angle.', instructions: ['Set bench to 30-45 degrees', 'Hold dumbbells at shoulder level', 'Press up and together', 'Lower with control'], muscleGroups: ['chest', 'shoulders', 'triceps'], primaryMuscle: 'chest', equipment: 'dumbbell', difficultyLevel: 'intermediate', category: 'hypertrophy', defaultSets: 3, defaultReps: '8-12', defaultRestSeconds: 75, tags: ['upper chest', 'push', 'dumbbell'] },
  { name: 'Cable Fly', description: 'Isolation chest exercise using cable machine for constant tension.', instructions: ['Set cables to chest height', 'Stand in middle with arms open', 'Bring arms together in front', 'Squeeze chest at peak'], muscleGroups: ['chest'], primaryMuscle: 'chest', equipment: 'cable', difficultyLevel: 'beginner', category: 'hypertrophy', defaultSets: 3, defaultReps: '12-15', defaultRestSeconds: 60, tags: ['isolation', 'fly', 'cable'] },
  { name: 'Push-Up', description: 'Bodyweight chest exercise, foundational movement.', instructions: ['Place hands shoulder-width apart', 'Keep body straight', 'Lower chest to floor', 'Push back up'], muscleGroups: ['chest', 'triceps', 'core'], primaryMuscle: 'chest', equipment: 'bodyweight', difficultyLevel: 'beginner', category: 'endurance', defaultSets: 3, defaultReps: '15-20', defaultRestSeconds: 45, tags: ['bodyweight', 'push', 'beginner'] },
  { name: 'Dumbbell Chest Fly', description: 'Open arm arc motion targets chest with stretch and contraction.', instructions: ['Lie on bench', 'Hold dumbbells over chest', 'Open arms wide in arc', 'Bring back together'], muscleGroups: ['chest'], primaryMuscle: 'chest', equipment: 'dumbbell', difficultyLevel: 'beginner', category: 'hypertrophy', defaultSets: 3, defaultReps: '10-14', defaultRestSeconds: 60, tags: ['isolation', 'chest', 'stretch'] },
  { name: 'Decline Bench Press', description: 'Targets lower chest using a decline bench angle.', instructions: ['Set bench to -15 to -30 degrees', 'Grip bar wider than shoulders', 'Lower to lower chest', 'Press up fully'], muscleGroups: ['chest', 'triceps'], primaryMuscle: 'chest', equipment: 'barbell', difficultyLevel: 'intermediate', category: 'strength', defaultSets: 3, defaultReps: '8-12', defaultRestSeconds: 75, tags: ['lower chest', 'compound', 'barbell'] },

  // ── BACK ───────────────────────────────────────────────
  { name: 'Barbell Deadlift', description: 'King of all lifts. Full posterior chain compound movement.', instructions: ['Stand with feet hip-width', 'Grip bar at hip width', 'Hinge hips back', 'Drive through floor to stand'], muscleGroups: ['back', 'glutes', 'hamstrings', 'core'], primaryMuscle: 'back', equipment: 'barbell', difficultyLevel: 'advanced', category: 'strength', defaultSets: 4, defaultReps: '3-6', defaultRestSeconds: 180, tags: ['compound', 'posterior chain', 'powerlifting'] },
  { name: 'Pull-Up', description: 'Classic bodyweight upper back exercise using a pull-up bar.', instructions: ['Hang from bar with overhand grip', 'Pull body up until chin clears bar', 'Lower with control'], muscleGroups: ['back', 'biceps'], primaryMuscle: 'back', equipment: 'pull_up_bar', difficultyLevel: 'intermediate', category: 'strength', defaultSets: 4, defaultReps: '6-10', defaultRestSeconds: 90, tags: ['bodyweight', 'compound', 'back'] },
  { name: 'Barbell Row', description: 'Bent-over row for full back thickness development.', instructions: ['Hinge forward 45-90 degrees', 'Pull bar to lower ribs', 'Squeeze shoulder blades', 'Lower with control'], muscleGroups: ['back', 'biceps'], primaryMuscle: 'back', equipment: 'barbell', difficultyLevel: 'intermediate', category: 'strength', defaultSets: 4, defaultReps: '6-10', defaultRestSeconds: 90, tags: ['compound', 'back', 'row'] },
  { name: 'Lat Pulldown', description: 'Machine exercise targeting lat width with pulldown motion.', instructions: ['Sit at cable machine', 'Grip bar wide overhead', 'Pull bar to upper chest', 'Return under control'], muscleGroups: ['back', 'biceps'], primaryMuscle: 'back', equipment: 'cable', difficultyLevel: 'beginner', category: 'hypertrophy', defaultSets: 3, defaultReps: '10-12', defaultRestSeconds: 75, tags: ['lat', 'pulldown', 'cable'] },
  { name: 'Seated Cable Row', description: 'Horizontal pulling exercise for mid-back thickness.', instructions: ['Sit at cable row machine', 'Brace core and sit tall', 'Pull handle to abdomen', 'Squeeze scapulae together'], muscleGroups: ['back', 'biceps'], primaryMuscle: 'back', equipment: 'cable', difficultyLevel: 'beginner', category: 'hypertrophy', defaultSets: 3, defaultReps: '10-12', defaultRestSeconds: 60, tags: ['row', 'back', 'cable'] },
  { name: 'Dumbbell Row', description: 'Single-arm dumbbell row for unilateral back development.', instructions: ['Place one knee on bench', 'Brace with opposite arm', 'Pull dumbbell to hip', 'Squeeze lat at top'], muscleGroups: ['back', 'biceps'], primaryMuscle: 'back', equipment: 'dumbbell', difficultyLevel: 'beginner', category: 'hypertrophy', defaultSets: 3, defaultReps: '10-12', defaultRestSeconds: 60, tags: ['unilateral', 'back', 'dumbbell'] },

  // ── SHOULDERS ──────────────────────────────────────────
  { name: 'Overhead Press (OHP)', description: 'Standing compound shoulder press with barbell.', instructions: ['Stand with bar at shoulder level', 'Press bar overhead until arms locked', 'Lower to collarbone', 'Brace core throughout'], muscleGroups: ['shoulders', 'triceps', 'core'], primaryMuscle: 'shoulders', equipment: 'barbell', difficultyLevel: 'intermediate', category: 'strength', defaultSets: 4, defaultReps: '5-8', defaultRestSeconds: 120, tags: ['compound', 'press', 'shoulders'] },
  { name: 'Dumbbell Lateral Raise', description: 'Isolation movement for lateral deltoid development.', instructions: ['Stand holding dumbbells', 'Raise arms to sides to shoulder height', 'Lower with control', 'Slight forward lean allowed'], muscleGroups: ['shoulders'], primaryMuscle: 'shoulders', equipment: 'dumbbell', difficultyLevel: 'beginner', category: 'hypertrophy', defaultSets: 3, defaultReps: '12-15', defaultRestSeconds: 60, tags: ['isolation', 'lateral', 'delts'] },
  { name: 'Face Pull', description: 'Cable exercise for rear delts and external rotators.', instructions: ['Set cable at face height', 'Pull rope to face with elbows high', 'Externally rotate at end', 'Return slowly'], muscleGroups: ['shoulders', 'back'], primaryMuscle: 'shoulders', equipment: 'cable', difficultyLevel: 'beginner', category: 'hypertrophy', defaultSets: 3, defaultReps: '15-20', defaultRestSeconds: 45, tags: ['rear delt', 'cable', 'health'] },
  { name: 'Arnold Press', description: 'Rotating dumbbell press that hits all three deltoid heads.', instructions: ['Hold dumbbells at chin with palms facing you', 'Rotate palms out as you press up', 'Reverse on the way down', 'Full range of motion'], muscleGroups: ['shoulders', 'triceps'], primaryMuscle: 'shoulders', equipment: 'dumbbell', difficultyLevel: 'intermediate', category: 'hypertrophy', defaultSets: 3, defaultReps: '10-12', defaultRestSeconds: 75, tags: ['press', 'rotation', 'delts'] },

  // ── BICEPS ─────────────────────────────────────────────
  { name: 'Barbell Curl', description: 'Classic mass-building bicep exercise with barbell.', instructions: ['Stand holding barbell at hip', 'Keep elbows at sides', 'Curl bar to chest level', 'Lower with control'], muscleGroups: ['biceps', 'forearms'], primaryMuscle: 'biceps', equipment: 'barbell', difficultyLevel: 'beginner', category: 'hypertrophy', defaultSets: 3, defaultReps: '8-12', defaultRestSeconds: 60, tags: ['curl', 'biceps', 'barbell'] },
  { name: 'Incline Dumbbell Curl', description: 'Long head bicep focus using incline bench for stretch.', instructions: ['Set bench to 60 degrees', 'Let arms hang naturally', 'Curl dumbbells up', 'Full squeeze at top'], muscleGroups: ['biceps'], primaryMuscle: 'biceps', equipment: 'dumbbell', difficultyLevel: 'intermediate', category: 'hypertrophy', defaultSets: 3, defaultReps: '10-12', defaultRestSeconds: 60, tags: ['curl', 'stretch', 'biceps'] },
  { name: 'Hammer Curl', description: 'Neutral grip curl targeting brachialis and brachioradialis.', instructions: ['Stand with palms facing each other', 'Curl with neutral grip', 'Full range of motion', 'Alternating or bilateral'], muscleGroups: ['biceps', 'forearms'], primaryMuscle: 'biceps', equipment: 'dumbbell', difficultyLevel: 'beginner', category: 'hypertrophy', defaultSets: 3, defaultReps: '10-14', defaultRestSeconds: 60, tags: ['hammer', 'neutral', 'biceps'] },
  { name: 'Cable Curl', description: 'Constant tension bicep curl using low cable pulley.', instructions: ['Attach bar to low pulley', 'Curl bar to chest height', 'Slow eccentric', 'Keep elbows fixed'], muscleGroups: ['biceps'], primaryMuscle: 'biceps', equipment: 'cable', difficultyLevel: 'beginner', category: 'hypertrophy', defaultSets: 3, defaultReps: '12-15', defaultRestSeconds: 45, tags: ['cable', 'curl', 'tension'] },

  // ── TRICEPS ────────────────────────────────────────────
  { name: 'Close-Grip Bench Press', description: 'Compound tricep exercise using a narrow barbell grip.', instructions: ['Grip bar at shoulder width or narrower', 'Tuck elbows to sides', 'Lower to lower chest', 'Press explosively'], muscleGroups: ['triceps', 'chest'], primaryMuscle: 'triceps', equipment: 'barbell', difficultyLevel: 'intermediate', category: 'strength', defaultSets: 3, defaultReps: '8-10', defaultRestSeconds: 75, tags: ['triceps', 'compound', 'close grip'] },
  { name: 'Tricep Pushdown', description: 'Cable isolation for all three tricep heads.', instructions: ['Set cable high', 'Grip bar overhand', 'Keep elbows tucked', 'Fully extend arms down'], muscleGroups: ['triceps'], primaryMuscle: 'triceps', equipment: 'cable', difficultyLevel: 'beginner', category: 'hypertrophy', defaultSets: 3, defaultReps: '12-15', defaultRestSeconds: 45, tags: ['triceps', 'pushdown', 'cable'] },
  { name: 'Skull Crusher', description: 'Lying tricep extension for long head isolation.', instructions: ['Lie on bench with EZ-bar', 'Start arms extended over face', 'Hinge at elbows to lower bar', 'Extend back up'], muscleGroups: ['triceps'], primaryMuscle: 'triceps', equipment: 'barbell', difficultyLevel: 'intermediate', category: 'hypertrophy', defaultSets: 3, defaultReps: '10-12', defaultRestSeconds: 60, tags: ['isolation', 'triceps', 'lying'] },
  { name: 'Overhead Tricep Extension', description: 'Long head tricep exercise in stretched position.', instructions: ['Hold dumbbell overhead', 'Hinge at elbows behind head', 'Extend arms fully', 'Keep upper arms vertical'], muscleGroups: ['triceps'], primaryMuscle: 'triceps', equipment: 'dumbbell', difficultyLevel: 'beginner', category: 'hypertrophy', defaultSets: 3, defaultReps: '12-15', defaultRestSeconds: 60, tags: ['overhead', 'triceps', 'stretch'] },

  // ── LEGS ───────────────────────────────────────────────
  { name: 'Barbell Squat', description: 'King of leg exercises. Full lower body compound movement.', instructions: ['Bar on upper traps', 'Feet shoulder-width apart', 'Squat below parallel', 'Drive through heels to stand'], muscleGroups: ['quads', 'glutes', 'hamstrings', 'core'], primaryMuscle: 'quads', equipment: 'barbell', difficultyLevel: 'intermediate', category: 'strength', defaultSets: 4, defaultReps: '5-8', defaultRestSeconds: 150, tags: ['squat', 'legs', 'compound'] },
  { name: 'Romanian Deadlift', description: 'Hinge pattern primarily targeting hamstrings and glutes.', instructions: ['Hold barbell at hip', 'Hinge forward keeping back flat', 'Feel hamstring stretch', 'Drive hips forward to stand'], muscleGroups: ['hamstrings', 'glutes', 'back'], primaryMuscle: 'hamstrings', equipment: 'barbell', difficultyLevel: 'intermediate', category: 'strength', defaultSets: 3, defaultReps: '8-12', defaultRestSeconds: 90, tags: ['RDL', 'hinge', 'hamstrings'] },
  { name: 'Leg Press', description: 'Machine compound leg exercise with adjustable range of motion.', instructions: ['Sit in leg press machine', 'Place feet shoulder-width on platform', 'Lower to 90 degrees', 'Press platform away'], muscleGroups: ['quads', 'glutes', 'hamstrings'], primaryMuscle: 'quads', equipment: 'machine', difficultyLevel: 'beginner', category: 'hypertrophy', defaultSets: 4, defaultReps: '10-15', defaultRestSeconds: 90, tags: ['machine', 'legs', 'quad'] },
  { name: 'Lunges', description: 'Unilateral leg exercise for balance and quad development.', instructions: ['Stand tall', 'Step forward and lower rear knee to floor', 'Push back to start', 'Alternate legs'], muscleGroups: ['quads', 'glutes', 'hamstrings'], primaryMuscle: 'quads', equipment: 'bodyweight', difficultyLevel: 'beginner', category: 'hypertrophy', defaultSets: 3, defaultReps: '12 each leg', defaultRestSeconds: 60, tags: ['unilateral', 'lunges', 'legs'] },
  { name: 'Leg Curl', description: 'Machine isolation for hamstrings in lying or seated position.', instructions: ['Lie face down on leg curl machine', 'Curl heels toward glutes', 'Squeeze hamstrings', 'Lower slowly'], muscleGroups: ['hamstrings'], primaryMuscle: 'hamstrings', equipment: 'machine', difficultyLevel: 'beginner', category: 'hypertrophy', defaultSets: 3, defaultReps: '12-15', defaultRestSeconds: 60, tags: ['isolation', 'hamstrings', 'machine'] },
  { name: 'Leg Extension', description: 'Machine isolation exercise for the quadriceps.', instructions: ['Sit in leg extension machine', 'Extend legs to full lockout', 'Squeeze quads', 'Lower with control'], muscleGroups: ['quads'], primaryMuscle: 'quads', equipment: 'machine', difficultyLevel: 'beginner', category: 'hypertrophy', defaultSets: 3, defaultReps: '12-15', defaultRestSeconds: 60, tags: ['isolation', 'quads', 'machine'] },
  { name: 'Calf Raise', description: 'Standing calf raise for gastrocnemius development.', instructions: ['Stand on edge of step', 'Lower heels below step', 'Rise on toes as high as possible', 'Hold briefly at top'], muscleGroups: ['calves'], primaryMuscle: 'calves', equipment: 'machine', difficultyLevel: 'beginner', category: 'hypertrophy', defaultSets: 4, defaultReps: '15-20', defaultRestSeconds: 45, tags: ['calves', 'isolation', 'gastroc'] },
  { name: 'Bulgarian Split Squat', description: 'Rear foot elevated unilateral squat for glutes and quads.', instructions: ['Rear foot elevated on bench', 'Front foot forward', 'Lower rear knee to floor', 'Drive through front heel'], muscleGroups: ['quads', 'glutes', 'hamstrings'], primaryMuscle: 'glutes', equipment: 'dumbbell', difficultyLevel: 'intermediate', category: 'strength', defaultSets: 3, defaultReps: '8-12 each leg', defaultRestSeconds: 90, tags: ['unilateral', 'glutes', 'squat'] },
  { name: 'Hip Thrust', description: 'Barbell glute bridge for maximum glute activation.', instructions: ['Sit against bench with barbell on hips', 'Drive hips to ceiling', 'Squeeze glutes at top', 'Lower with control'], muscleGroups: ['glutes', 'hamstrings'], primaryMuscle: 'glutes', equipment: 'barbell', difficultyLevel: 'intermediate', category: 'hypertrophy', defaultSets: 4, defaultReps: '10-15', defaultRestSeconds: 75, tags: ['glutes', 'hip thrust', 'barbell'] },
  { name: 'Goblet Squat', description: 'Front-loaded squat with dumbbell or kettlebell. Great for form.', instructions: ['Hold weight at chest level', 'Stand with feet shoulder-width', 'Squat deep keeping weight close', 'Stand and repeat'], muscleGroups: ['quads', 'glutes', 'core'], primaryMuscle: 'quads', equipment: 'kettlebell', difficultyLevel: 'beginner', category: 'strength', defaultSets: 3, defaultReps: '10-12', defaultRestSeconds: 75, tags: ['squat', 'goblet', 'beginners'] },

  // ── CORE ───────────────────────────────────────────────
  { name: 'Plank', description: 'Isometric core stability exercise.', instructions: ['Forearms on floor', 'Body forms straight line', 'Brace all core muscles', 'Hold position'], muscleGroups: ['core', 'abs'], primaryMuscle: 'core', equipment: 'bodyweight', difficultyLevel: 'beginner', category: 'endurance', defaultSets: 3, defaultReps: '30-60 seconds', defaultRestSeconds: 45, tags: ['plank', 'isometric', 'core'] },
  { name: 'Cable Crunch', description: 'Weighted cable ab crunch for progressive overload on abs.', instructions: ['Kneel at cable pulley', 'Hold rope at sides of head', 'Crunch downward rounding lower back', 'Return to start'], muscleGroups: ['abs', 'core'], primaryMuscle: 'abs', equipment: 'cable', difficultyLevel: 'beginner', category: 'hypertrophy', defaultSets: 3, defaultReps: '12-15', defaultRestSeconds: 60, tags: ['abs', 'weighted', 'cable'] },
  { name: 'Hanging Leg Raise', description: 'Advanced ab exercise hanging from pull-up bar.', instructions: ['Hang from bar', 'Raise legs to horizontal or vertical', 'Control the lower', 'Avoid swinging'], muscleGroups: ['abs', 'core', 'forearms'], primaryMuscle: 'abs', equipment: 'pull_up_bar', difficultyLevel: 'advanced', category: 'strength', defaultSets: 3, defaultReps: '10-15', defaultRestSeconds: 60, tags: ['hanging', 'abs', 'advanced'] },
  { name: 'Russian Twist', description: 'Rotational core exercise with or without weight.', instructions: ['Sit at 45 degrees', 'Feet elevated off floor', 'Rotate torso side to side', 'Keep core braced'], muscleGroups: ['core', 'abs'], primaryMuscle: 'abs', equipment: 'bodyweight', difficultyLevel: 'beginner', category: 'endurance', defaultSets: 3, defaultReps: '20 total', defaultRestSeconds: 45, tags: ['rotation', 'obliques', 'core'] },
  { name: 'Ab Wheel Rollout', description: 'Full core extension and contraction with ab wheel.', instructions: ['Start kneeling with wheel in hands', 'Roll forward extending fully', 'Pull back with abs', 'Keep lower back protected'], muscleGroups: ['core', 'abs', 'back'], primaryMuscle: 'core', equipment: 'none', difficultyLevel: 'advanced', category: 'strength', defaultSets: 3, defaultReps: '8-12', defaultRestSeconds: 60, tags: ['rollout', 'core', 'advanced'] },

  // ── CARDIO ─────────────────────────────────────────────
  { name: 'Treadmill Running', description: 'Steady-state or interval cardio on treadmill.', instructions: ['Set desired speed and incline', 'Maintain steady pace', 'Land mid-foot', 'Keep upright posture'], muscleGroups: ['cardio', 'calves', 'quads'], primaryMuscle: 'cardio', equipment: 'machine', difficultyLevel: 'beginner', category: 'cardio', defaultSets: 1, defaultReps: '20-30 min', defaultRestSeconds: 0, tags: ['cardio', 'running', 'endurance'] },
  { name: 'Rowing Machine', description: 'Full body cardio with low impact on joints.', instructions: ['Sit in rower with feet strapped', 'Drive legs, then lean back, then pull arms', 'Return in reverse order', 'Maintain steady rhythm'], muscleGroups: ['cardio', 'back', 'core', 'legs'], primaryMuscle: 'cardio', equipment: 'machine', difficultyLevel: 'beginner', category: 'cardio', defaultSets: 1, defaultReps: '15-20 min', defaultRestSeconds: 0, tags: ['cardio', 'rowing', 'full body'] },
  { name: 'Burpees', description: 'Full body conditioning exercise combining squat, push-up, and jump.', instructions: ['Stand tall', 'Drop to squat position and kick feet back', 'Perform push-up', 'Jump feet in and explode up with arms overhead'], muscleGroups: ['full_body', 'cardio'], primaryMuscle: 'cardio', equipment: 'bodyweight', difficultyLevel: 'intermediate', category: 'cardio', defaultSets: 3, defaultReps: '10-15', defaultRestSeconds: 45, tags: ['burpees', 'conditioning', 'full body'] },
  { name: 'Jump Rope', description: 'High-intensity cardio and coordination exercise.', instructions: ['Hold handles lightly', 'Jump with both feet', 'Use wrists to rotate rope', 'Land softly on balls of feet'], muscleGroups: ['cardio', 'calves', 'shoulders'], primaryMuscle: 'cardio', equipment: 'none', difficultyLevel: 'beginner', category: 'cardio', defaultSets: 3, defaultReps: '60-120 seconds', defaultRestSeconds: 30, tags: ['jump rope', 'cardio', 'conditioning'] },
  { name: 'Kettlebell Swing', description: 'Hip-hinge explosive movement for power and cardio.', instructions: ['Hike kettlebell back between legs', 'Explosively drive hips forward', 'Let bell swing to chest height', 'Hinge back and repeat'], muscleGroups: ['glutes', 'hamstrings', 'back', 'cardio'], primaryMuscle: 'glutes', equipment: 'kettlebell', difficultyLevel: 'intermediate', category: 'cardio', defaultSets: 4, defaultReps: '15-20', defaultRestSeconds: 60, tags: ['kettlebell', 'swing', 'power'] },
  { name: 'Battle Ropes', description: 'Full body conditioning using heavy rope waves.', instructions: ['Stand with knees slightly bent', 'Alternate arms in wave motion', 'Maintain strong core', 'Various patterns: waves, slams, circles'], muscleGroups: ['shoulders', 'arms', 'core', 'cardio'], primaryMuscle: 'cardio', equipment: 'none', difficultyLevel: 'intermediate', category: 'cardio', defaultSets: 4, defaultReps: '30-45 seconds', defaultRestSeconds: 30, tags: ['battle ropes', 'conditioning', 'intense'] },
  { name: 'Box Jump', description: 'Plyometric exercise for explosive power and athleticism.', instructions: ['Stand facing box', 'Bend knees and swing arms', 'Jump and land softly on box', 'Step down safely'], muscleGroups: ['quads', 'glutes', 'calves', 'cardio'], primaryMuscle: 'quads', equipment: 'none', difficultyLevel: 'intermediate', category: 'cardio', defaultSets: 4, defaultReps: '8-10', defaultRestSeconds: 60, tags: ['plyometric', 'jump', 'explosive'] },
];

const seedExercises = async () => {
  try {
    await connectDB();
    const existing = await Exercise.countDocuments();
    if (existing > 0) {
      console.log(`⚠️  ${existing} exercises already exist. Skipping seed.`);
      console.log('   To reseed, first delete all exercises from the DB.');
      process.exit(0);
    }

    await Exercise.insertMany(exercises);
    console.log(`✅ Successfully seeded ${exercises.length} exercises into Gymmix DB`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed failed:', error.message);
    process.exit(1);
  }
};

seedExercises();
